Fix encoding to prevent SytnaxError
The character encoding is called `utf-8`, not `utf8`.
The latter causes the following exception under Python 3.7.4:
```
SyntaxError: encoding problem: utf8
````

Please see [PEP 263](https://www.python.org/dev/peps/pep-0263/) for more detailed information about the `coding` directive.